name: Fennel 0.0.5 on Lua 5.4

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - '**.lua'
      - '**.fnl'
      - '**.sh'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - '**.lua'
      - '**.fnl'
      - '**.sh'
      - 'Makefile'

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linter
        uses: ./.github/workflows/actions/lua-5.4
        with:
          bash-script-path: '.github/workflows/linter.sh'
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        uses: ./.github/workflows/actions/lua-5.4
        with:
          bash-script-path: '.github/workflows/tests.sh'
  examples:
    name: Examples
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Examples
        uses: ./.github/workflows/actions/lua-5.4
        with:
          bash-script-path: '.github/workflows/examples.sh'
