name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - '**.lua'
      - '**.fnl'
      - '**.sh'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - '**.lua'
      - '**.fnl'
      - '**.sh'
      - 'Makefile'

jobs:
  lua_5_3:
    name: Lua 5.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        id: tests-lua-5-3
        uses: ./.github/workflows/actions/lua-5.3
        with:
          bash-script-path: '.github/workflows/tests.sh'


