name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - '**.lua'
      - '**.fnl'
      - '**.sh'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - '**.lua'
      - '**.fnl'
      - '**.sh'
      - 'Makefile'

jobs:
  lua_5_4:
    name: Lua 5.4
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        id: tests-lua-5-4
        uses: ./
        with:
          bash-script-path: 'test-and-lint.sh'
